### ISSUE TITLE
v7.1.0 is hanging on plugin startup

### ISSUE THREAD

**Issue by indigodomo** [FlyingDiver/Indigo-Harmony#1]
Tracked it down to HubClient.py line 47:

            self.auth_token = harmony_auth.get_auth_token(self.harmony_ip, self.harmony_port)

That call never comes back rendering the plugin hung. Interestingly, this seems to have started sometime between 3:54pm CST on 1/26 and 12:27pm CST on 1/27.

**Comment by indigodomo** [comment]
AH HA. The IP address of the hub changed. So the way you have to fix it is to 1) uncheck the comm enabled checkbox in the device list, then 2) reload the plugin (causing the server to kill it). The plugin won't try to start the device so you can edit the IP. Not sure what the fix is but that's pretty terrible behavior in the pyharmony library. I'd recommend maybe pinging the IP before trying to create the HubClient?

**Comment by FlyingDiver** [comment]
Fixed in 7.1.1.
