### ISSUE TITLE
Socket Failure with harmony hub firmware 4.15.264

### ISSUE THREAD

**Issue by EagleDTW** [FlyingDiver/Indigo-Harmony#11]
Having an issue with Socket Failure with harmony hub firmware 4.15.264 and indigo plugin 7.3.1, the IP address is correct, how do I join the Harmony beta program and which Hub firmware version should work?

**Comment by FlyingDiver** [comment]
4.15.264 is the correct version.  I don't know anything about a Beta program.  It's not required.

You do need to make sure XMPP is enabled.  In the mobile app, go to:

Harmony Setup -> Add/Edit -> Remote & Hub.  Make sure XMPP is NOT disabled.

If you're still having problems, set the plugin to debug logging, restart the plugin, and post the log file.

**Comment by EagleDTW** [comment]
Of course you would solve my hub comm problem in 30 seconds, started using and I’m loving it - thanks!
