### ISSUE TITLE
XMPP Deja vu Groundhog Day

### ISSUE THREAD

**Issue by Hackencrash** [FlyingDiver/Indigo-Harmony#12]
I don't know how many times this XMPP setting has caught me out over the years.

Can we be a bit proactive here so instead of the log being filled with [i]runConcurrentThread 2 arguments (1 given)[/i] errors, the Harmony Plugin simply logs:

[b]Enable XMPP from the Harmony phone app Settings Menu>Harmony Setup>Add/Edit Devices & Activities>Remote & Hub>Disable XMPP>Cancel (to enable)[/b]

Great plugin by the way.

**Comment by FlyingDiver** [comment]
Fixed in 7.3.2
