### ISSUE TITLE
power of command functioning like a power toggle command

### ISSUE THREAD

**Issue by SearchCz** [FlyingDiver/Indigo-Harmony#15]
I have an Indigo 2021.1 action group called "lets watch nothing" that is meant to function just like the power off button on my remote. Works great when anything is playing. But if the TV (etc) is already off, this action group turns it on. 

I'm running plugin v 7.3.2. 

My harmony hub is runnng hub software v 4.15.290

**Comment by FlyingDiver** [comment]
Does the plugin action "Power Off" not work?

**Comment by SearchCz** [comment]
Correct. 

If the equipment is on, “power off” turns it off.

If the equipment is off, “power off” turns it on.

**Comment by FlyingDiver** [comment]
Is that the only command in the Indigo action group? If not, show me the complete list in the group.

**Comment by SearchCz** [comment]
These are my options:

**Comment by FlyingDiver** [comment]
You can't do attachments via email.  You need to post them on the GitHub website.

**Comment by SearchCz** [comment]
Sorry, I didn't know that. 
<img width="264" alt="Screen Shot 2021-11-01 at 8 34 30 PM" src="https://user-images.githubusercontent.com/67106658/139889154-c14f1b92-396b-4b9d-a710-758bc849a37e.png">

Not sure if this could be related to the plugin, but I also have a weird problem of my TV intermittently turning itself off. I've temporarily disabled the plugin to see if that issue goes away.

**Comment by FlyingDiver** [comment]
So when the system is off, if you have the plugin send the "Power Off" command, then it turns back on?

Honestly, that sounds like a bug in the API.  We're just sending the 'Start Activity" command with the specified code for "Power Off".

I might be able to work around it by just not sending the command if the plugin thinks the system is off.  Not sure if that'll break things or not.

**Comment by SearchCz** [comment]
It seems like you might be sending “power toggle” instead of “power off”. I see to recall that the old Harmony remotes didn’t differentiate between “power off” and “power on” and just handled everything as simply “power”. 

I added an indigo variable & virtual device  to track the TV on/off status, and only allow that “power off” harmony command to proceed if Indigo thinks the TV is on.  I’ll how that goes.

**Comment by FlyingDiver** [comment]
Actually, I'm not sending either.  I'm sending "set Activity to Power Off", and it's up to the hub to get that correct.

**Comment by FlyingDiver** [comment]
Nothing to fix.
