### ISSUE TITLE
Feature Request: Add action to refresh data 

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Harmony#16]
About once a day the hub state becomes stale. For example: the device state says "Watch YouTubeTV" when it's powered off.  To remedy this, I reload the plugin and it updates. 

Not sure if this is a bug, but it would be great to have an Action that refreshes the data or reloads the plugin.  I would use this to refresh or reload a few times a day.

**Comment by FlyingDiver** [comment]
I'll have to see if that's possible.  The state is refreshed when the hub sends updates.  Not sure if there's a way to force that.

**Comment by ryanbuckner** [comment]
Understood. Is there a way to script a reload?

**Comment by FlyingDiver** [comment]
No script needed. 
<img width="923" alt="Screen Shot 2022-01-17 at 12 01 57 PM" src="https://user-images.githubusercontent.com/72976/149811185-ec8c0c7b-dc37-44fd-9ccc-5c169321fd7e.png">

**Comment by ryanbuckner** [comment]
huh.  Guess I never knew that was there. Thanks!

**Comment by gt3mike** [comment]
How does the plugin get the Harmony Hub state when it starts up? Is there a
way to trigger that periodically in the plugin?

**Comment by FlyingDiver** [comment]
> How does the plugin get the Harmony Hub state when it starts up? Is there a way to trigger that periodically in the plugin?

I would have to go dig into the code to determine that.  I really don't know off the top of my head.

**Comment by FlyingDiver** [comment]
No way to force an update without disconnected and reconnecting to the hub, so just restart.
