### ISSUE TITLE
Having to reload after a long idle time

### ISSUE THREAD

**Issue by umtauscher** [FlyingDiver/Indigo-Harmony#2]
After a few hours, the harmony plugin seems to loose connection to the hub. at least it's not notified about any changes any more that are triggered by another remote.
Trying to uses something like "Mute" in that situation doesn't work either in that state.

I have to reload manually form the Indigo Menue

**Comment by FlyingDiver** [comment]
I'm looking into this now.  I primarily control my Hubs using the companion or elite remotes.  I'll be watching the Indigo state of the hub to see if it's following along with the remote commands.

**Comment by FlyingDiver** [comment]
I just can't reproduce this.

**Comment by umtauscher** [comment]
Thanks, it didn't happen for about a month now. I suppose it was on the Harmony side...
Cheers Wilhelm
