### ISSUE TITLE
Socket test failure

### ISSUE THREAD

**Issue by cfriedberg** [FlyingDiver/Indigo-Harmony#6]
That said simply unplugging the hub and waiting 10 secs and plugging it back in enabled COMMs. However stopping and starting the server made the Philemon come back. It seems like the hub needs to reconnect after startup for the problem to go away.

**Comment by FlyingDiver** [comment]
Philemon?

**Comment by FlyingDiver** [comment]
I think this is the same as https://github.com/FlyingDiver/Indigo-Harmony/issues/5
