### ISSUE TITLE
Drop Down Menu Addition

### ISSUE THREAD

**Issue by rjayyyy** [FlyingDiver/Indigo-Harmony#7]
As per our convo over at the Indigo Forums, possibly a drop down selector in this window to identify which activity is executing would make logical sense for the GUI.

Indigo thread: https://forums.indigodomo.com/viewtopic.php?f=212&t=22114&p=174386#p174386

thanks again

**Comment by FlyingDiver** [comment]
Can't change the existing event without breaking current implementations.   Is it worth adding an additional event for this when the same result can be achieved using a condition?  Probably not.
